name: cewers_flutter
description: CEWERS mobile application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^5.0.0+hotfix.5
  shared_preferences: ^0.5.7
  cloudinary_client: ^0.0.9
  carousel_slider: ^2.1.0
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.6+1
  observable: ^0.22.2
  location: ^3.0.0
  get_it: ^4.0.2
  rxdart: ^0.24.0
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cloudinary.json
    - assets/backgrounds/
    - assets/backgrounds/2.0x/
    - assets/backgrounds/3.0x/
    - assets/icons/
    - assets/icons/tabs/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

  fonts:
    - family: Playfair
      fonts:
        - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-Italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 300
          style: italic
